--liquibase formatted sql
--changeset patrick:1

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    priority VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    deadline DATE,
    planned_at DATE,
    start_time TIMESTAMP(6),
    end_time TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    user_id BIGINT NOT NULL,

    CONSTRAINT pk_tasks PRIMARY KEY (id),
    CONSTRAINT tasks_priority_check CHECK ( priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT') ),
    CONSTRAINT tasks_status_check CHECK ( status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD') )
);

ALTER TABLE tasks ADD CONSTRAINT fk_tasks_user
    FOREIGN KEY (user_id) REFERENCES users(id);